openapi: 3.0.0
info:
  contact:
    email: robipolli@gmail.com
    name: Roberto Polli
    url: https://twitter.com/ioggstream
  description: |
    #### Documentazione
    Il servizio Ora esatta ritorna l'ora del server in formato RFC5424 (syslog).

    `2018-12-30T12:23:32Z`

    ##### Sottosezioni
    E' possibile utilizzare - con criterio - delle sottosezioni.

    #### Note

    Il servizio non richiede autenticazione, ma va' usato rispettando gli
    header di throttling esposti in conformita' alle Linee Guida del Modello di interoperabilita'.

    #### Informazioni tecniche ed esempi

    Esempio:

    ```
    http http://localhost:8443/datetime/v1/echo
    {
      'datetime': '2018-12-30T12:23:32Z'
    }
    ```
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ora esatta.
  version: 1.0.0
  x-api-id: 00000000-0000-0000-0000-000000000000
  x-audience:
  - public
  x-summary: Questo servizio ritorna la data e l'ora attuali in UTC.
servers:
- description: Test server
  url: https://api.example.com/
- description: Development server
  url: https://localhost:8443/datetime/v1
tags:
- description: Retrieve informations
  externalDocs:
    url: http://docs.my-api.com/pet-operations.htm
  name: public
paths:
  /:
    get:
      operationId: api.index
      responses:
        200:
          content:
            text/html: {}
          description: foo
      summary: metadata
  /my-attributes:
    get:
      operationId: api.get_attrs
      responses:
        200:
          content:
            application/json: {}
          description: Show all user attributes stored in the spid session.
      summary: Return all passed user attributes.
  /config:
    get:
      operationId: spid.get_config
      responses:
        200:
          content:
            application/json: {}
          description: foo
      summary: metadata
  /echo:
    get:
      description: |
        Ritorna un timestamp in formato RFC5424
        prendendola dal server attuale.
      operationId: api.get_echo
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Timestamps'
          description: |
            Il server ha ritornato il timestamp.
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
        default:
          $ref: '#/components/responses/default'
      summary: Ritorna un timestamp in formato RFC5424.
      tags:
      - public
  /aa/attributes/{attribute}:
    get:
      operationId: api.get_attribute_simple
      parameters:
        - name: attribute
          schema:
            type: string
          in: path
      responses:
        200:
          description: Return a given attribute, taken from the AA.
  /aa/consent-attributes/{attribute}:
    get:
      summary: Ritorna un attributo che richiede un consenso dell'utente.
      operationId: api.get_attribute_consent
      parameters:
      - name: attribute
        schema:
          type: string
        in: path
      responses:
        200:
          description: Return a given attribute, taken from the AA.
  /metadata:
    get:
      operationId: spid.get_metadata
      responses:
        200:
          description: foo
      summary: metadata
  /saml:
    get:
      operationId: spid.get_saml
      parameters:
      - description: Request Login to IdP
        in: query
        name: sso
        schema:
          type: string
      - description: Request Logout to IdP
        in: query
        name: slo
        schema:
          type: string
      - description: Receive Logout from IdP
        in: query
        name: sls
        schema:
          type: string
      responses:
        200:
          content:
            text/html: {}
          description: foo
      summary: Manage the following saml operations.
    post:
      operationId: spid.post_saml
      parameters:
      - description: Receive Login from IdP
        in: query
        name: acs
        schema:
          type: string
      - description: Request Logout to IdP
        in: query
        name: slo
        schema:
          type: string
      - description: Receive Logout from IdP
        in: query
        name: sls
        schema:
          type: string
      responses:
        200:
          content:
            text/html: {}
          description: foo
      summary: Manage the following saml operations.
  /status:
    get:
      description: |
        Ritorna lo stato dell'applicazione. A scopo
        di test, su base randomica puo' ritornare
        un errore.
      operationId: api.get_status
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Timestamps'
          description: |
            Il server ha ritornato lo status. In caso di problemi
            ritorna sempre un problem+json.
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
        default:
          $ref: '#/components/responses/default'
      summary: Ritorna lo stato dell'applicazione.
      tags:
      - public
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        type: integer
  responses:
    400BadRequest:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Bad Request
    404NotFound:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Not Found
    429TooManyRequests:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Too many requests
      headers:
        Retry-After:
          description: |-
            Retry contacting the endpoint *at least* after seconds.
            See https://tools.ietf.org/html/rfc7231#section-7.1.3
          schema:
            format: int32
            type: integer
        X-RateLimit-Limit:
          description: The number of allowed requests in the current period
          schema:
            format: int32
            type: integer
        X-RateLimit-Remaining:
          description: The number of remaining requests in the current period
          schema:
            format: int32
            type: integer
        X-RateLimit-Reset:
          description: The number of seconds left in the current period
          schema:
            format: int32
            type: integer
    503ServiceUnavailable:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Service Unavailable
      headers:
        Retry-After:
          description: |-
            Retry contacting the endpoint *at least* after seconds.
            See https://tools.ietf.org/html/rfc7231#section-7.1.3
          schema:
            format: int32
            type: integer
    default:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Unexpected error
  schemas:
    Problem:
      properties:
        detail:
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
          type: string
        instance:
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          format: uri
          type: string
        status:
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
          type: string
        type:
          default: about:blank
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          example: https://tools.ietf.org/html/rfc7231#section-6.6.4
          format: uri
          type: string
      type: object
    Timestamps:
      description: Un Timestamp in RFC5424
      properties:
        timestamp:
          example: '2018-12-30T12:23:32Z'
          format: date-time
          type: string
      type: object
